### ISSUE TITLE
Nuxt

### ISSUE THREAD

**Issue by entity** [wobsoriano/v-satori#1]
Hi,

I followed your Nuxt 3 example, is it possible to have Satori return a PNG, as browsers don't seem to return the SVG output.

Thanks

**Comment by wobsoriano** [comment]
Try setting the header `Content-Type`

```ts
import { satori } from 'v-satori' // helper from new release
import Image from '@/components/Image.vue'

export default eventHandler(async (event) => {
  const query = useQuery(event)

  const svg = await satori(Image, {
    props: {
      title: query.title,
      website: query.website
    },
    width: 1200,
    height: 627,
    fonts: []
  })

  setHeader(event, 'Content-Type', 'image/svg+xml')

  return svg
})
```

**Comment by wobsoriano** [comment]
https://v-satori.vercel.app/api/og?title=OG%20Image%20Generator%20using%20Nuxt%20and%20Satori&website=v3.nuxtjs.org

```ts
setHeader(event, 'Content-Type', 'image/svg+xml')
```

**Comment by entity** [comment]
> Try setting the header `Content-Type`
> 
> ```ts
> import { satori } from 'v-satori' // helper from new release
> import Image from '@/components/Image.vue'
> 
> export default eventHandler(async (event) => {
>   const query = useQuery(event)
> 
>   const svg = await satori(Image, {
>     props: {
>       title: query.title,
>       website: query.website
>     },
>     width: 1200,
>     height: 627,
>     fonts: []
>   })
> 
>   setHeader(event, 'Content-Type', 'image/svg+xml')
> 
>   return svg
> })
> ```

Thanks for the reply, will this return a PNG then?

The SVG output is what my browser didn’t like for the open graph, I suppose it expects some form of PNG or something

**Comment by entity** [comment]
Hey @wobsoriano, this works great in production!

However locally I get:
```
[Vue warn]: Component /Users/charlie/Documents/Development/Projects/charliejoseph.com/components/Image.vue is missing template or render function.

```

Any reason why?
